### ISSUE TITLE
Haskell arguments notation

### ISSUE THREAD

**Issue by bennyty** [glguy/advent2017#2]
Hey, really appreciate reading over how you solved these problems. I noticed you used a `{ ^ name }` notation to document (maybe?) the names for arguments?

`getInput :: Int {- ^ day number -} -> IO String`

Do you know what the keyword for this feature is? What is it called / where can I read more about it?

**Comment by glguy** [comment]
This is the syntax used by [haddock](https://www.haskell.org/haddock/doc/html/index.html), which is the standard tool for generating documentation for Haskell libraries and executables.

In particular a `|` indicates that the documentation pertains to the following syntactic element and `^` to the preceding one.

This works with `-- | text`, `{- | text -}`, `-- ^ text` and `{- ^ text -}`

Here's an example of how this renders: [https://glguy.net/advent2017/Day05/Main.html#v:solve](https://glguy.net/advent2017/Day05/Main.html#v:solve)

**Comment by bennyty** [comment]
Thanks!
